### ISSUE TITLE
Error during build: 'basename: missing operand'

### ISSUE THREAD

**Issue by blackhawk101x** [adjacentlink/emane-tutorial#19]
During the initial build of the emane-tutorial, i get the following error error:

```
basename: missing operand
Try 'basename --help' for more information.
```
 and then it prints out a massive ```sed``` command from the script.  Am I missing an installation? I followed the installation guide for emane. Can the script be modified to print out a more useful error message?

This is on CentOS 7

**Comment by sgalgano** [comment]
You have probably not installed olsrd.
