### ISSUE TITLE
Demo1 - Activity 2 - Emulation Event Log Event Generator

### ISSUE THREAD

**Issue by legit13** [adjacentlink/emane-tutorial#21]
### The code after the instruction: "Remove the NO-host-eventservice file and re-start the demonstration" has a small error.

`[me@host 1]$ rm -f NO-host-eventservice`

should be changed to

`[me@host 1]$ rm -f NO-host-emaneeventservice`

Thanks!

**Comment by sgalgano** [comment]
Thanks. The wiki has been updated.
