### ISSUE TITLE
Network topology change from single hop to multi-hop in demo-8

### ISSUE THREAD

**Issue by szl0144** [adjacentlink/emane-tutorial#22]
Hi,

I am using demo-8 to do some tests, the topology I am going to use is two hops network with just one receiver rather than 10, can you give me some ideas about which configure files I need to change in demo-8? I saw some configurations the platform.xml may be related to the topology in demo-2 but I didn't find this kind of file in demo-8. 

Best,
Shaoyi

**Comment by sgalgano** [comment]
Demonstration 8 uses [precomputed](https://github.com/adjacentlink/emane-tutorial/blob/master/8/tdmanem.xml#L11) pathloss. Use pathloss events to set the pathloss between nodes to achieve the desired multihop topology.

You can generate and send pathloss in a number of ways: use emaneevent-pathloss ([see demo 1 step 7](https://github.com/adjacentlink/emane-tutorial/wiki/Demonstration-1)), use [emaneeventservice](https://github.com/adjacentlink/emane-tutorial/wiki/Demonstration-1#activity-2---emulation-event-log-event-generator), or write your own [python script](https://github.com/adjacentlink/emane-tutorial/blob/master/1/bridge_with10.py).

**Comment by szl0144** [comment]
> Demonstration 8 uses [precomputed](https://github.com/adjacentlink/emane-tutorial/blob/master/8/tdmanem.xml#L11) pathloss. Use pathloss events to set the pathloss between nodes to achieve the desired multihop topology.
> 
> You can generate and send pathloss in a number of ways: use emaneevent-pathloss ([see demo 1 step 7](https://github.com/adjacentlink/emane-tutorial/wiki/Demonstration-1)), use [emaneeventservice](https://github.com/adjacentlink/emane-tutorial/wiki/Demonstration-1#activity-2---emulation-event-log-event-generator), or write your own [python script](https://github.com/adjacentlink/emane-tutorial/blob/master/1/bridge_with10.py).

**Comment by szl0144** [comment]
I see, do you mean I need to set node 1's path loss be a small value and set node 2 to node 10's path loss be a large value, and all multicast packets will be sent to node 1 firstly, then they will be sent to its destination from node 1 due to the optimal routing path?

Best,
Shaoyi
