### ISSUE TITLE
LXC 4 Support

### ISSUE THREAD

**Issue by tomhalford** [adjacentlink/emane-tutorial#26]
Is there a fix hanging around that allows the tutorial to run with LXC 4.x?

**Comment by eschreiber-alink** [comment]
Try deleting line 353 and 383 of scripts/democtl-host.

lxc.net.2.type = empty                                                                                               
lxc.net.2.flags=up

becomes

lxc.net.2.type = empty                                                                                               

in both places. The flags config may no longer be needed for the loopback device.

**Comment by tomhalford** [comment]
That didn't do the trick. I was able to get the demo started by additionally modifying line 335 to support LXC versions >= 3. The demo starts and I see the screen output per the wiki. However, after starting up the demo, when I try to ssh into node-1, I am told:

ssh: Could not resolve hostname node-1: Temporary failure in name resolution

Could this be LXC version related or perhaps due to another issue? I tried to ping the nodes directly (10.100.0.1/2) and wasn't able to connect. Also, when I stop the demo, lxc-stop indicates that the nodes are not running.

**Comment by tomhalford** [comment]
Also, if the tutorial is known to work off-the-shelf in 18.04, then I can start from a new VM. I'm not married to 20.04 vs. 18.04.

**Comment by tomhalford** [comment]
> Try deleting line 353 and 383 of scripts/democtl-host.
> 
> lxc.net.2.type = empty
> lxc.net.2.flags=up
> 
> becomes
> 
> lxc.net.2.type = empty
> 
> in both places. The flags config may no longer be needed for the loopback device.

Thanks, Eric. That plus a mod to the logic on line 335 to allow major versions >= 3 did the trick.
