### ISSUE TITLE
OLSR Topology Not Drawing

### ISSUE THREAD

**Issue by tomhalford** [adjacentlink/emane-tutorial#27]
When I run the olsrlinkview script, all of the nodes are drawn on top of each other (top panel in the screenshot below). I can manually pull the nodes out of the pile at the top left and see that there is in fact a link being detected by the script (bottom panel in the screenshot below). I've verified the same behavior in Demo 1. I'm at a loss as to how to debug this.  

I'm running on a fresh Ubuntu 18.04 LTS virtual machine and worked through the build process per the tutorial documentation. The only build anomaly I ran into is that python3-pynodestatviz wouldn't build. It references the package "python3-pmw" which doesn't appear to exist anywhere for Debian releases. Installing pmw via pip3 didn't help matters. python-pynodestatviz built and installed fine.

![VirtualBox_vEMANE-18_30_07_2020_11_46_35](https://user-images.githubusercontent.com/64798840/88956265-5dc06180-d25a-11ea-847b-23c4ebe5d2c1.png)

**Comment by sgalgano** [comment]
This tool does not automatically place nodes. Drag the nodes where you like then hit `Ctrl-s` to save the locations. This creates `$HOME/.pynodestatviz-locations.xml`.

Here is an example `pynodestatviz-locations.xml`:

```xml
<nodestatviz-locations>
  <nodes>
    <node name="10" x="15.0" y="10.0"/>
    <node name="10.100.0.8" x="260.0" y="158.0"/>
    <node name="10.100.0.9" x="258.0" y="106.0"/>
    <node name="10.100.0.6" x="154.0" y="237.0"/>
    <node name="10.100.0.7" x="234.0" y="202.0"/>
    <node name="10.100.0.4" x="65.0" y="154.0"/>
    <node name="10.100.0.5" x="85.0" y="202.0"/>
    <node name="10.100.0.2" x="94.0" y="58.0"/>
    <node name="10.100.0.3" x="70.0" y="111.0"/>
    <node name="10.100.0.1" x="155.0" y="25.0"/>
  </nodes>
</nodestatviz-locations>
```

**Comment by tomhalford** [comment]
Thanks, Steven. I’m glad to hear that it’s a tool limitation versus a build/environment problem on my end.
