### ISSUE TITLE
How to debug TDMA timing in tutorial 8?

### ISSUE THREAD

**Issue by tomhalford** [adjacentlink/emane-tutorial#28]
I'm running the TDMA tutorial and I'm seeing a large fraction of slots (>10%) being missed. I'm not sure where to begin to debug  address this issue. Something strikes me as fundamentally wrong with my setup if the nodes cannot keep up with their receive schedule. Also, when I trim the simulation down to just two nodes I am seeing about 10% of slots being missed as well. 

I'm running EMANE in a VM on a brand new laptop (i9 processor), so I don't think that the emulation platform is underpowered. Where do I start with an issue like this?

**Comment by sgalgano** [comment]
Mileage will vary depending on the host operating system, with bare metal virtualization being best. Your issue is most likely interrupt latency related to virtualization. If your host is linux, make sure you are using performance CPU governors. I would recommend trying a native install of the tutorial.

**Comment by tomhalford** [comment]
Thanks, Steven. As you suggested, I tried on bare metal with performance CPU governors and I'm now see 0% packet losses on pings across the tutorial 8 network. The RxSlotStatusTable looks much better too. I appreciate the help!

**Comment by gardnedn** [comment]
@sgalgano Hi, I'm also trying to make use of tutorial 8. Maybe too basic of a question, but how does one send a message through EMANE. So if you have the nodes set up, how would you send a custom message throughout the network? I've been reading the developer documentation, possibly could be creating a transport, but was double checking if there was a more recommended approach.
