### ISSUE TITLE
Trouble setting up LXC version 3 using democtl-host as an example

### ISSUE THREAD

**Issue by WorksWellWithOthers** [adjacentlink/emane-tutorial#30]
Using democtl-host as an example I'm trying to Launch EMANE in LXC manually.

lxc.hook.autodev.sh
```
#!/bin/bash -
if ! [ -c /dev/net/tun ]; then
 mkdir -p /dev/net
 mknod -m 666 /dev/net/tun c 10 200
fi
```

lxc.conf.1
```
lxc.uts.name=node-1
lxc.net.0.type=veth
lxc.net.0.name=eth1
lxc.net.0.flags=up
lxc.net.0.link=emanenode0
lxc.net.0.hwaddr=02:00:01:01:00:01
lxc.net.0.ipv4.address=10.99.0.1/24
lxc.net.0.veth.pair=veth1.1

lxc.net.2.type = empty
lxc.net.2.flags=up

lxc.console.path = none
lxc.tty.max = 1
lxc.pty.max = 128
lxc.cgroup.devices.allow = a
lxc.mount.auto = proc sys cgroup

lxc.autodev = 1
lxc.hook.autodev = /persist/1/var/run/lxc.hook.autodev.sh
lxc.apparmor.profile = unconfined
```

Command:
`lxc-execute -f persist/1/var/run/lxc.conf.1 -n node-1 -o /persist/1/var/log/lxc-execute.log.1 -- scripts/demo-init . 1`

Error Message:
```
lxc-execute: node-1: start.c: proc_pidfd_open: 1607 Function not implemented - Failed to send signal through pidfd
lxc-execute: node-1: start.c: lxc_spawn: 1785 Failed to setup cgroup limits for container "node-1"
lxc-execute: node-1: start.c: __lxc_start: 2019 Failed to spawn container "node-1"
lxc-execute: node-1: tools/lxc_execute.c: main: 245 Failed run an application inside container
```

I tried using python3-lxc bindings thinking it would be easier but I can't make a container at all. Hard to find tutorials/docs on it as well.

**Comment by bullr** [comment]
Having a related issue on a new Ubuntu 20.04 LTS server install with emane installed from the git/deb binaries for 20.04. I did not have this issue on the older CentOS7 install that had emane manually installed via source.

emane-tutorial/0# ./demo-start 
Creating bridge: emanenode0
waiting for emanenode0...found
kernel.sched_rt_runtime_us = -1
**_Unsupported LXC version_**

**Comment by sgalgano** [comment]
I do not believe these issues are related. @bullr pull emane-tutorial. I just merged 8763e9cf14c5b41b19029da81fd05e44a0006f0b to master.

**Comment by bullr** [comment]
that got the containers starting, thanks!

**Comment by sgalgano** [comment]
@WorksWellWithOthers have you taken a look at [letce2](https://github.com/adjacentlink/letce2), [letce2-plugin-lxc](https://github.com/adjacentlink/letce2-plugin-lxc) and [letce2-tutorial](https://github.com/adjacentlink/letce2-tutorial)? letce2 is better suited for authoring experiments than trying to derive from emane-tutorial.

**Comment by WorksWellWithOthers** [comment]
I'll take a look at the letce2-tutorials. Thank you.
