### ISSUE TITLE
Tutorial 0 - level 0 fails

### ISSUE THREAD

**Issue by lesliemulder** [adjacentlink/emane-tutorial#4]
In trying to run the tutorial 0 level 0 I get the following responses:

root@cedardrome:/home/m/emane-tutorial/0# ls
bypassmac.xml eventservice.xml NO-node-gpsd
bypassnem.xml gpsdlocationagent1.xml NO-node-routing
bypassphy.xml gpsdlocationagent2.xml persist
demo-start Makefile platform1.xml
demo-stop NO-host-emaneeventservice platform2.xml
eelgenerator.xml NO-node-emane routing1.conf
eventdaemon1.xml NO-node-emaneeventd routing2.conf
eventdaemon2.xml NO-node-emanetransportd transvirtual.xml

root@cedardrome:/home/m/emane-tutorial/0# ./demo-start
Creating bridge: emanenode0
kernel.sched_rt_runtime_us = -1
Starting lxc instance: node-1
Starting lxc instance: node-2
root@cedardrome:/home/m/emane-tutorial/0#

The demo-start script terminates immedaitely.

The log file for node 1 is

lxc-execute 1450896658.716 ERROR    lxc_sync - sync.c:__sync_wake:62 - sync wake failure : Broken pipe
lxc-execute 1450896658.716 ERROR    lxc_start - start.c:__lxc_start:1121 - failed to spawn 'node-1'

The log file for node 2 is the same, excepting that it notes node-2 not node-1

**Comment by sgalgano** [comment]
What linux distribution are you using?

**Comment by lesliemulder** [comment]
Ubuntu 14.0.4

-------- Original message --------

**Comment by lesliemulder** [comment]
44~14.04.1-Ubuntu SMP Web Dec 2 10:00:35 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sgalgano** [comment]
We are not able to reproduce the issue you are seeing with any of our 14.04 systems (server or vm guest).

From your initial message it appears the issue may be with your LXC installation.

**Comment by lesliemulder** [comment]
It would be great if you could gvie me a hint as to what to do try to address or diagnose the issue with my LXC installaion.
